### ISSUE TITLE
Make responsive transform fn customisable

### ISSUE THREAD

**Issue by lorenzomigliorero** [cogentParadigm/postcss-variants#1]
Hi!
Great work first of all!

In the [responsive.js](https://github.com/cogentParadigm/postcss-variants/blob/master/src/variants/responsive.js) built-in plugin, I'd would be great to have the chance to customize the `selector.value` interpolation:

```diff
   const parser = require('postcss-selector-parser');
 
+  opts.transform = opts.transform || function(selector, suffix) {
+    return `${selector.value}-${suffix}`
+  };
+
   const createTransformer = suffix => {
     return selectors => {
       selectors.walk(selector => {
           if (selector.type == "class") {
-            selector.value += `-${suffix}`
+            selector.value = opts.transform(selector, suffix)
           }
       });
     };
```

`selector.value += "-${suffix}"` is not so common, and many popular CSS frameworks are prepending the suffix insted `sm:font-size-100`.

**Comment by cogentParadigm** [comment]
Hi @lorenzomigliorero. Thanks for the feedback. Feel free to submit a PR with this change.

**Comment by lorenzomigliorero** [comment]
Here we go! https://github.com/cogentParadigm/postcss-variants/pull/2
